import { Shield, Lock, Cpu, Globe, Zap, ArrowLeft, CheckCircle2 } from 'lucide-react';
import { motion } from 'motion/react';
import { Link } from 'react-router-dom';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function Security() {
  const securityFeatures = [
    {
      title: "End-to-End Encryption",
      icon: <Lock className="w-6 h-6 text-blue-600" />,
      content: "All data transmitted between your device and our servers is encrypted using industry-standard TLS 1.3 protocols. Your medical records are encrypted at rest using AES-256."
    },
    {
      title: "HIPAA Compliance",
      icon: <Shield className="w-6 h-6 text-emerald-600" />,
      content: "We strictly adhere to HIPAA regulations for the protection of sensitive patient health information. Our infrastructure is audited regularly for compliance."
    },
    {
      title: "Distributed Infrastructure",
      icon: <Globe className="w-6 h-6 text-purple-600" />,
      content: "Our AI models run on a distributed, secure network with multi-region redundancy to ensure 99.99% uptime and data availability."
    },
    {
      title: "Neural Integrity",
      icon: <Cpu className="w-6 h-6 text-rose-600" />,
      content: "Our AI processing pipeline includes multiple validation layers to ensure the integrity and accuracy of clinical insights generated by our models."
    }
  ];

  return (
    <div className="bg-white min-h-screen selection:bg-blue-100 selection:text-blue-900">
      <Navbar />
      
      <main className="pt-32 pb-24 px-6">
        <div className="max-w-4xl mx-auto">
          <Link to="/" className="inline-flex items-center gap-2 text-slate-500 hover:text-blue-600 transition-colors mb-12 group">
            <ArrowLeft className="w-4 h-4 group-hover:-translate-x-1 transition-transform" />
            <span className="text-sm font-bold uppercase tracking-widest">Back to Home</span>
          </Link>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="space-y-6 mb-16"
          >
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-emerald-50 text-emerald-600 rounded-full text-[10px] font-black uppercase tracking-[0.2em] border border-emerald-100">
              <Shield className="w-3 h-3 fill-current" />
              Security Architecture
            </div>
            <h1 className="text-5xl lg:text-7xl font-black tracking-tight text-slate-900 leading-none">Security First.</h1>
            <p className="text-xl text-slate-500 font-medium leading-relaxed max-w-2xl">
              We've engineered MediFlow AI with a zero-trust security model. Your medical data is protected by the most advanced technical standards in the industry.
            </p>
          </motion.div>

          <div className="grid gap-8 mb-20">
            {securityFeatures.map((feature, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: i * 0.1 }}
                className="p-10 bg-slate-50 rounded-[3rem] border border-slate-100 hover:shadow-xl transition-all group"
              >
                <div className="flex gap-8">
                  <div className="w-16 h-16 bg-white rounded-2xl flex items-center justify-center flex-shrink-0 shadow-inner group-hover:scale-110 transition-transform duration-500">
                    {feature.icon}
                  </div>
                  <div>
                    <h3 className="text-2xl font-black text-slate-900 mb-4">{feature.title}</h3>
                    <p className="text-slate-500 font-medium leading-relaxed">{feature.content}</p>
                  </div>
                </div>
              </motion.div>
            ))}
          </div>

          <div className="bg-slate-900 rounded-[4rem] p-16 text-white relative overflow-hidden">
            <div className="absolute top-0 right-0 w-64 h-64 bg-blue-500/10 rounded-full blur-[80px]"></div>
            <div className="relative z-10">
              <h2 className="text-3xl font-black mb-8">Security Certifications</h2>
              <div className="grid sm:grid-cols-2 gap-8">
                {[
                  "SOC 2 Type II Certified",
                  "HIPAA Compliant Infrastructure",
                  "GDPR Data Protection Ready",
                  "ISO 27001 Information Security"
                ].map((cert, i) => (
                  <div key={i} className="flex items-center gap-4">
                    <div className="w-6 h-6 bg-blue-500/20 text-blue-400 rounded-full flex items-center justify-center">
                      <CheckCircle2 className="w-4 h-4" />
                    </div>
                    <span className="font-bold text-slate-300">{cert}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
